### ISSUE TITLE
Add Minimal Working Example of Adding Custom Images to `ggalignment`

### ISSUE THREAD

**Issue by TheCedarPrince** [aftonsteps/ggalignment#5]
Hey @aftonsteps ,

Could you add a minimal working example on how exactly to add custom images to `ggalignment`? Perhaps either in the README or in the docstring for `ggalignment` itself? Thank you!

**Comment by aftonsteps** [comment]
I've added this at the end of the main {ggalignment} vignette, for local files as well as for URL's. Let me know if it's unclear, though!

**Comment by TheCedarPrince** [comment]
You're the bomb! I will check it out later today and share it with some friends! :smile:
